# 04 — Early Regime-Aware Trading Signals
## <b> Adrian Vazquez </b>


--- 

Early Features
↓
Predicted Regime
↓
Trading Signal
↓
Accuracy

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from scipy.stats import linregress
early_regime = pd.read_csv("../data/processed/early_regime_dataset.csv")
early_regime.head(2)

,market_id,horizon,question,slug,total_n_obs,early_n_obs,early_obs_share,total_time_seconds,early_time_seconds,early_time_share,...,bayesian_fair_probability,mispricing,abs_mispricing,abs_surprise,cluster,market_regime,early_max_drawdown,early_reversals,early_entropy,target
0,248594,0.25,Will Hunter Biden be federally indicted by May...,will-hunter-biden-be-federally-indicted-by-may...,1826,457,0.250274,7163979.0,1825177.0,0.254771,...,0.038462,0.018462,0.018462,0.02,0,Information Processing,0.935484,8,0.661563,1
1,248594,0.50,Will Hunter Biden be federally indicted by May...,will-hunter-biden-be-federally-indicted-by-may...,1826,913,0.500000,7163979.0,3553194.0,0.495981,...,0.038462,0.018462,0.018462,0.02,0,Information Processing,0.935484,24,0.693147,1

In [6]:
# Can we generate a valid signal from a highly restricted information set?
df_25 = early_regime[early_regime["horizon"] == 0.25].copy()

,market_id,horizon,question,slug,total_n_obs,early_n_obs,early_obs_share,total_time_seconds,early_time_seconds,early_time_share,...,bayesian_fair_probability,mispricing,abs_mispricing,abs_surprise,cluster,market_regime,early_max_drawdown,early_reversals,early_entropy,target
0,248594,0.25,Will Hunter Biden be federally indicted by May...,will-hunter-biden-be-federally-indicted-by-may...,1826,457,0.250274,7163979.0,1825177.0,0.254771,...,0.038462,0.018462,0.018462,0.0200,0,Information Processing,0.935484,8,0.661563,1
1,248594,0.50,Will Hunter Biden be federally indicted by May...,will-hunter-biden-be-federally-indicted-by-may...,1826,913,0.500000,7163979.0,3553194.0,0.495981,...,0.038462,0.018462,0.018462,0.0200,0,Information Processing,0.935484,24,0.693147,1
2,248594,0.75,Will Hunter Biden be federally indicted by May...,will-hunter-biden-be-federally-indicted-by-may...,1826,1370,0.750274,7163979.0,5392799.0,0.752766,...,0.038462,0.018462,0.018462,0.0200,0,Information Processing,0.946237,30,0.689944,1
3,249778,0.25,MLB: Cincinnati Reds vs. Pittsburgh Pirates 20...,mlb-cin-pit-2023-04-02,23,6,0.260870,100797.0,18011.0,0.178686,...,0.600000,0.050000,0.050000,0.4500,1,Anchored / Noisy,0.000000,0,0.000000,0
4,249778,0.50,MLB: Cincinnati Reds vs. Pittsburgh Pirates 20...,mlb-cin-pit-2023-04-02,23,12,0.521739,100797.0,43197.0,0.428554,...,0.600000,0.050000,0.050000,0.4500,1,Anchored / Noisy,0.000000,0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,255337,0.50,Fed rate cut by December 18?,fed-rate-cut-by-december-18,4655,2328,0.500107,16761599.0,8380800.0,0.500000,...,0.900000,-0.099500,0.099500,0.0005,0,Information Processing,0.556842,123,0.689701,1
125,255337,0.75,Fed rate cut by December 18?,fed-rate-cut-by-december-18,4655,3492,0.750161,16761599.0,12574799.0,0.750215,...,0.900000,-0.099500,0.099500,0.0005,0,Information Processing,0.556842,248,0.692934,1
126,255410,0.25,US inflation >0.4% from Feb to March 2024?,us-inflation-0pt4-from-feb-to-march-2024,8,2,0.250000,25199.0,3599.0,0.142823,...,0.600000,0.065000,0.065000,0.5350,1,Anchored / Noisy,0.000000,0,-0.000000,0
127,255410,0.50,US inflation >0.4% from Feb to March 2024?,us-inflation-0pt4-from-feb-to-march-2024,8,4,0.500000,25199.0,10799.0,0.428549,...,0.600000,0.065000,0.065000,0.5350,1,Anchored / Noisy,0.026316,1,0.636514,0
128,255410,0.75,US inflation >0.4% from Feb to March 2024?,us-inflation-0pt4-from-feb-to-march-2024,8,6,0.750000,25199.0,17999.0,0.714274,...,0.600000,0.065000,0.065000,0.5350,1,Anchored / Noisy,0.070175,1,0.500402,0