In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import sys
import polars as pl
import pyarrow
import gc
from itertools import combinations
import matplotlib.pyplot as plt
sys.path.append(str(Path("..")))
# Backtest dataset construction - universe tradable daily 
from src.ingest.ingest_backtest import build_backtest_warmup_parquets
from src.universe.pair_universe import (build_universe_metadata_from_symbol_parquets,apply_sector_fixes,generate_candidate_pairs,
                                        build_daily_tradable_universe,)

Within same-sector Nasdaq-100 stocks, larger-cap or more liquid names may incorporate information earlier. If this is true, lagged returns of the leader should have explanatory power over future returns of the follower.

In [2]:
BACKTEST_DATA_DIR = Path("../data/backtest_1min_with_warmup_by_symbol")

SECTOR_FIXES = {"ASML": "SEMICONDUCTORS & RELATED DEVICES",
                "CCEP": "BEVERAGES",
                "PDD": "RETAIL-CATALOG & MAIL-ORDER HOUSES",
                "TRI": "SERVICES-BUSINESS SERVICES, NEC",}

# 1. Build Universe Metadata
universe_df = build_universe_metadata_from_symbol_parquets(BACKTEST_DATA_DIR)
universe_df = apply_sector_fixes(universe_df,SECTOR_FIXES)
# 2. Generate Same-Sector Candidate Pairs
df_candidate_pairs = generate_candidate_pairs(universe_df)

In [3]:
df_candidate_pairs

    stock_a stock_b                                           sector
0      CCEP     KDP                                        BEVERAGES
1      CCEP     PEP                                        BEVERAGES
2       KDP     PEP                                        BEVERAGES
3      AMGN    GILD  BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)
4      CHTR   CMCSA            CABLE & OTHER PAY TELEVISION SERVICES
..      ...     ...                                              ...
185    SHOP    TEAM                    SERVICES-PREPACKAGED SOFTWARE
186    SHOP    TTWO                    SERVICES-PREPACKAGED SOFTWARE
187    SNPS    TEAM                    SERVICES-PREPACKAGED SOFTWARE
188    SNPS    TTWO                    SERVICES-PREPACKAGED SOFTWARE
189    TEAM    TTWO                    SERVICES-PREPACKAGED SOFTWARE

[190 rows x 3 columns]

In [ ]:
adi = pd.read_parquet("../data/backtest_1min_with_warmup_by_symbol/ADI_backtest_1min_warmup.parquet")
amat = pd.read_parquet("../data/backtest_1min_with_warmup_by_symbol/AMAT_backtest_1min_warmup.parquet")
amd = pd.read_parquet("../data/backtest_1min_with_warmup_by_symbol/AMD_backtest_1min_warmup.parquet")

# test
def add_log_return(df):
    df['log_return'] = np.log(df['close'] / df['close'].shift(1))
    return df
dfs = { 'adi' : adi,'amat' : amat, 'amd': amd}
for symbol, df in dfs.items():
    dfs[symbol] = add_log_return(df)
# two candidate merge 
adi_amat = pd.merge(adi[['date', 'log_return']], amat[['date', 'log_return']], on='date', suffixes=('adi', 'amat'))
# adi & amd
adi_amd = pd.merge(adi[['date', 'log_return']], amd[['date', 'log_return']], on='date', suffixes=('adi', 'amd'))
pairs = {"ADI_AMAT": adi_amat,"ADI_AMD": adi_amd}
lags = [1,5,15,30]
results = []
for pair_name, df in pairs.items():
    col1 = [c for c in df.columns if "adi" in c][0]
    col2 = [c for c in df.columns if col1 != c and "log_return" in c][0]
    for lag in lags:
        corr_forward = (df[col1].corr(df[col2].shift(-lag)))
        corr_reverse = (df[col2].corr(df[col1].shift(-lag)))
        results.append([pair_name,lag,corr_forward,corr_reverse])
results = pd.DataFrame(results,columns=["pair","lag","A_to_B","B_to_A"])
results["lead_score"] = (results["A_to_B"]- results["B_to_A"])
results

       pair  lag    A_to_B    B_to_A  lead_score
0  ADI_AMAT    1  0.004685  0.020605   -0.015920
1  ADI_AMAT    5 -0.003520 -0.003696    0.000176
2  ADI_AMAT   15  0.007188  0.010060   -0.002873
3  ADI_AMAT   30  0.000296  0.002476   -0.002180
4   ADI_AMD    1  0.005376  0.019947   -0.014571
5   ADI_AMD    5 -0.000682 -0.002218    0.001536
6   ADI_AMD   15  0.000774  0.003551   -0.002777
7   ADI_AMD   30 -0.000906  0.003449   -0.004355

In [5]:
from pathlib import Path

DATA_DIR = Path("../data/backtest_1min_with_warmup_by_symbol")
LAGS = [1, 5, 15, 30]

def load_symbol_returns(symbol, data_dir=DATA_DIR):
    path = data_dir / f"{symbol}_backtest_1min_warmup.parquet"
    df = pd.read_parquet(path)
    df = df[["date", "close"]].copy()
    df["log_return"] = np.log(df["close"] / df["close"].shift(1))
    return df[["date", "log_return"]].dropna()


def compute_pair_lead_lag(stock_a, stock_b, sector=None, lags=LAGS):
    a = load_symbol_returns(stock_a).rename(columns={"log_return": "r_a"})
    b = load_symbol_returns(stock_b).rename(columns={"log_return": "r_b"})
    pair_df = pd.merge(a, b, on="date", how="inner").dropna()
    rows = []
    for lag in lags:
        a_to_b = pair_df["r_a"].corr(pair_df["r_b"].shift(-lag))
        b_to_a = pair_df["r_b"].corr(pair_df["r_a"].shift(-lag))
        lead_score = a_to_b - b_to_a
        rows.append({
            "stock_a": stock_a,
            "stock_b": stock_b,
            "sector": sector,
            "lag": lag,
            "A_to_B": a_to_b,
            "B_to_A": b_to_a,
            "lead_score": lead_score,
            "abs_lead_score": abs(lead_score),
            "empirical_leader": stock_a if lead_score > 0 else stock_b,
            "empirical_follower": stock_b if lead_score > 0 else stock_a,
            "n_obs": len(pair_df)
        })
    return pd.DataFrame(rows)

all_results = []

for _, row in df_candidate_pairs.iterrows():
    pair_result = compute_pair_lead_lag(
        stock_a=row["stock_a"],
        stock_b=row["stock_b"],
        sector=row["sector"],
        lags=LAGS
    )
    all_results.append(pair_result)

lead_lag_results = pd.concat(all_results, ignore_index=True)
lead_lag_clean = lead_lag_results.query("n_obs >= 10000").copy()
lead_lag_clean.sort_values("abs_lead_score", ascending=False).head(20)

,stock_a,stock_b,sector,lag,A_to_B,B_to_A,lead_score,abs_lead_score,empirical_leader,empirical_follower,n_obs
246,AVGO,MPWR,SEMICONDUCTORS & RELATED DEVICES,15,0.000449,-0.086163,0.086613,0.086613,AVGO,MPWR,12991
408,MELI,PYPL,"SERVICES-BUSINESS SERVICES, NEC",1,0.005223,0.065919,-0.060696,0.060696,PYPL,MELI,477455
708,MSFT,SNPS,SERVICES-PREPACKAGED SOFTWARE,1,0.054634,0.000429,0.054206,0.054206,MSFT,SNPS,477455
334,MPWR,NXPI,SEMICONDUCTORS & RELATED DEVICES,15,0.042501,-0.008463,0.050965,0.050965,MPWR,NXPI,12991
138,AMAT,MPWR,SEMICONDUCTORS & RELATED DEVICES,15,0.011290,-0.039127,0.050417,0.050417,AMAT,MPWR,12991
676,INTU,MSFT,SERVICES-PREPACKAGED SOFTWARE,1,-0.001523,0.048300,-0.049824,0.049824,MSFT,INTU,477455
54,INSM,VRTX,PHARMACEUTICAL PREPARATIONS,15,0.045382,-0.003079,0.048461,0.048461,INSM,VRTX,12991
224,ASML,NVDA,SEMICONDUCTORS & RELATED DEVICES,1,0.003750,0.049794,-0.046044,0.046044,NVDA,ASML,477455
160,AMD,ASML,SEMICONDUCTORS & RELATED DEVICES,1,0.046654,0.002959,0.043696,0.043696,AMD,ASML,477455
16,CHTR,CMCSA,CABLE & OTHER PAY TELEVISION SERVICES,1,0.008401,0.051989,-0.043587,0.043587,CMCSA,CHTR,477455
604,CRWD,SNPS,SERVICES-PREPACKAGED SOFTWARE,1,0.048544,0.005123,0.043421,0.043421,CRWD,SNPS,416961
120,AMAT,ASML,SEMICONDUCTORS & RELATED DEVICES,1,0.048432,0.006145,0.042287,0.042287,AMAT,ASML,477455
416,PYPL,TRI,"SERVICES-BUSINESS SERVICES, NEC",1,0.041099,-0.000273,0.041372,0.041372,PYPL,TRI,477455
216,ASML,MRVL,SEMICONDUCTORS & RELATED DEVICES,1,0.002136,0.042092,-0.039956,0.039956,MRVL,ASML,477455
636,DDOG,SNPS,SERVICES-PREPACKAGED SOFTWARE,1,0.046145,0.006247,0.039898,0.039898,DDOG,SNPS,416961
484,ADBE,SNPS,SERVICES-PREPACKAGED SOFTWARE,1,0.047220,0.007866,0.039354,0.039354,ADBE,SNPS,477455
330,MPWR,NVDA,SEMICONDUCTORS & RELATED DEVICES,15,-0.034400,0.004047,-0.038447,0.038447,NVDA,MPWR,12991
396,DASH,MELI,"SERVICES-BUSINESS SERVICES, NEC",1,0.042439,0.004555,0.037884,0.037884,DASH,MELI,213555
208,ASML,MCHP,SEMICONDUCTORS & RELATED DEVICES,1,0.006508,0.044369,-0.037861,0.037861,MCHP,ASML,477455
220,ASML,MU,SEMICONDUCTORS & RELATED DEVICES,1,0.003300,0.039913,-0.036613,0.036613,MU,ASML,477455

In [8]:
lead_lag_clean["n_obs"].describe()

count       708.000000
mean     389031.870056
std      158986.032952
min       12991.000000
25%      416961.000000
50%      477455.000000
75%      477455.000000
max      477455.000000
Name: n_obs, dtype: float64

In [9]:
lead_lag_clean.groupby("lag")["n_obs"].median()

lag
1     477455.0
5     477455.0
15    477455.0
30    477455.0
Name: n_obs, dtype: float64

In [10]:
lead_lag_clean.groupby("empirical_leader").size()

empirical_leader
ADBE     22
ADI      16
ADP       5
ADSK     11
ALNY      9
AMAT     21
AMD      36
AMGN      2
AMZN      2
APP       5
ASML     16
AVGO     21
CCEP      3
CDNS     21
CHTR      2
CMCSA     2
CRWD     31
CSGP      6
CTSH      2
DASH     11
DDOG     31
EA       27
EXC       2
FTNT      2
GILD      2
GOOG      4
GOOGL     3
INSM      5
INTC     33
INTU     13
KDP       5
MCHP     18
MELI      4
MPWR     19
MRVL     26
MSFT     34
MU       29
NVDA     33
NXPI     16
PANW      2
PDD       2
PEP       4
PLTR     35
PYPL     13
REGN      5
SNPS     11
STX       2
TEAM     19
TRI       6
TSLA      4
TTWO      9
TXN      28
VRSK      4
VRTX      5
WDAY      3
WDC       2
XEL       2
ZS        2
dtype: int64

In [11]:
lead_lag_clean.groupby(["sector","empirical_leader"]).size()

sector                                                empirical_leader
BEVERAGES                                             CCEP                 3
                                                      KDP                  5
                                                      PEP                  4
BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)       AMGN                 2
                                                      GILD                 2
CABLE & OTHER PAY TELEVISION SERVICES                 CHTR                 2
                                                      CMCSA                2
COMPUTER PERIPHERAL EQUIPMENT, NEC                    FTNT                 2
                                                      PANW                 2
COMPUTER STORAGE DEVICES                              STX                  2
                                                      WDC                  2
ELECTRIC & OTHER SERVICES COMBINED                    EXC                  2
                                                      XEL                  2
MOTOR VEHICLES & PASSENGER CAR BODIES                 TSLA                 4
PHARMACEUTICAL PREPARATIONS                           ALNY                 9
                                                      INSM                 5
                                                      REGN                 5
                                                      VRTX                 5
RETAIL-CATALOG & MAIL-ORDER HOUSES                    AMZN                 2
                                                      PDD                  2
SEMICONDUCTORS & RELATED DEVICES                      ADI                 16
                                                      AMAT                21
                                                      AMD                 36
                                                      ASML                16
                                                      AVGO                21
                                                      INTC                33
                                                      MCHP                18
                                                      MPWR                19
                                                      MRVL                26
                                                      MU                  29
                                                      NVDA                33
                                                      NXPI                16
                                                      TXN                 28
SERVICES-BUSINESS SERVICES, NEC                       CSGP                 6
                                                      DASH                11
                                                      MELI                 4
                                                      PYPL                13
                                                      TRI                  6
SERVICES-COMPUTER PROCESSING & DATA PREPARATION       ADP                  5
                                                      VRSK                 4
                                                      WDAY                 3
SERVICES-COMPUTER PROGRAMMING SERVICES                CTSH                 2
                                                      ZS                   2
SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.  APP                  5
                                                      GOOG                 4
                                                      GOOGL                3
SERVICES-PREPACKAGED SOFTWARE                         ADBE                22
                                                      ADSK                11
                                                      CDNS                21
                                                      CRWD                31
                                                      DDOG                31
                                                      EA                  27
                                                      INTU                13
                                                      MSFT                34
                                                      PLTR                35
                                                      SNPS                11
                                                      TEAM                19
                                                      TTWO                 9
dtype: int64

In [ ]:
leader_counts = (lead_lag_clean["empirical_leader"].value_counts().reset_index())
leader_counts.columns = ["symbol", "count"]

# 1. Crear el gráfico de barras ordenado de mayor a menor
fig = px.bar(
    leader_counts,
    x="symbol",
    y="count",
    title="Frecuencia de Liderazgo por Acción (Efecto Lead-Lag)",
    labels={"symbol": "Acción (Ticker)", "count": "Veces como Líder"},
    text_auto=True,  # Muestra el número exacto sobre cada barra
    color="count",  # Aplica un degradado de color según el conteo
    color_continuous_scale="Viridis",
)

# 2. Mejorar el diseño para que sea fácil de leer
fig.update_layout(
    xaxis_tickangle=-45,  # Inclina los tickers si son muchos (tienes 95)
    xaxis={"categoryorder": "total descending"},  # Asegura el orden descendente
    plot_bgcolor="white",  # Fondo limpio
    height=600,  # Altura ajustable para acomodar los 95 símbolos
)

# 3. Mostrar el gráfico
fig.show()

In [14]:
lead_lag_clean.groupby("lag")["abs_lead_score"].describe()

,count,mean,std,min,25%,50%,75%,max
lag,,,,,,,,
1,177.0,0.015758,0.012543,0.000104,0.005185,0.013563,0.024017,0.060696
5,177.0,0.002786,0.002386,0.000038,0.001021,0.002299,0.003789,0.014330
15,177.0,0.007978,0.010304,0.000086,0.002665,0.005576,0.008994,0.086613
30,177.0,0.003540,0.003522,0.000048,0.001371,0.002637,0.004573,0.025752

In [15]:
lag_1 = lead_lag_clean.query("lag == 1").copy()
lag_1["empirical_leader"].value_counts()

empirical_leader
AMD      12
NVDA     11
INTC     10
MSFT     10
PLTR     10
MRVL      9
DDOG      9
MU        8
CRWD      8
AMAT      7
ADBE      7
EA        7
TXN       6
MCHP      5
TEAM      5
ADI       4
PYPL      4
CDNS      4
AVGO      3
DASH      3
TTWO      3
PEP       2
INSM      2
REGN      2
VRTX      2
NXPI      2
CSGP      2
ADP       2
GOOGL     2
INTU      2
KDP       1
GILD      1
CMCSA     1
FTNT      1
STX       1
EXC       1
TSLA      1
PDD       1
ASML      1
TRI       1
WDAY      1
CTSH      1
GOOG      1
ADSK      1
Name: count, dtype: int64

Sin avanzar más:

La señal parece concentrarse en lag=1 minuto.
La distribución de líderes no parece uniforme.
Aparecen nombres repetidamente (AMD, NVDA, INTC, MSFT, PLTR).
La métrica está produciendo una estructura interpretable, no puro ruido.

--- 
# Validación estadística del efecto lead-lag

In [36]:
msft= pd.read_parquet("../data/backtest_1min_with_warmup_by_symbol/AMD_backtest_1min_warmup.parquet")
snps = pd.read_parquet("../data/backtest_1min_with_warmup_by_symbol/NVDA_backtest_1min_warmup.parquet")

def add_log_return(df):
    # Fórmula correcta: ln( Price_t / Price_t-1 )
    df['log_return'] = np.log(df['close'] / df['close'].shift(1))
    return df
add_log_return(snps)
add_log_return(msft)
amd_nvda = pd.merge(msft[['date', 'log_return']], snps[['date', 'log_return']], on='date', suffixes=('_msft', '_snps'))
amd_nvda

                      date  log_return_msft  log_return_snps
0      2021-06-01 09:15:00              NaN              NaN
1      2021-06-01 09:16:00        -0.000370        -0.000153
2      2021-06-01 09:17:00         0.000123         0.000000
3      2021-06-01 09:18:00         0.000246        -0.000381
4      2021-06-01 09:19:00         0.000000        -0.000387
...                    ...              ...              ...
477451 2026-02-04 15:56:00        -0.001586        -0.000946
477452 2026-02-04 15:57:00        -0.003977         0.000287
477453 2026-02-04 15:58:00        -0.002643         0.001175
477454 2026-02-04 15:59:00        -0.000249        -0.002380
477455 2026-02-04 16:00:00         0.002095         0.000517

[477456 rows x 3 columns]

In [37]:
def lead_score(x, y, lag=1):
    a_to_b = x.corr(y.shift(-lag))
    b_to_a = y.corr(x.shift(-lag))
    return a_to_b - b_to_a

def permutation_test_lead_score(x,y,lag=1,n_permutations=1000,random_state=42):
    rng = np.random.default_rng(random_state)
    real_score = lead_score(x, y, lag)
    random_scores = []
    y_clean = y.dropna().values
    for _ in range(n_permutations):
        y_perm = rng.permutation(y_clean)
        y_perm = pd.Series(
            y_perm,
            index=y.dropna().index)
        score = lead_score( x.loc[y_perm.index],y_perm,lag)
        random_scores.append(score)
    random_scores = np.array(random_scores)
    p_value = np.mean( np.abs(random_scores)>=np.abs(real_score))

    return {"real_score": real_score,"random_mean": random_scores.mean(),
            "random_std": random_scores.std(),"p_value": p_value,"random_scores": random_scores}

result = permutation_test_lead_score(amd_nvda["log_return_msft"],amd_nvda["log_return_snps"],lag=1)
result

{'real_score': np.float64(0.0021254219370133824),
 'random_mean': np.float64(-7.5391717447962e-05),
 'random_std': np.float64(0.002062638069602675),
 'p_value': np.float64(0.274),
 'random_scores': array([-1.49050680e-04,  9.85028445e-04,  9.92420121e-04, -1.61419194e-03,
         2.24718885e-03,  4.57800460e-03, -2.83024129e-04, -1.08426814e-03,
         2.82579664e-03, -2.22318374e-03,  2.13307782e-03, -1.32445827e-03,
         2.03850661e-03, -1.19478779e-03, -1.05027677e-03, -3.58873074e-03,
         5.59167053e-05, -1.87468517e-03, -1.31217980e-03,  6.12621021e-04,
        -5.48977393e-04, -1.26988076e-03,  8.18064793e-04, -1.43082825e-03,
        -2.22579859e-05, -2.42785220e-03, -2.59706548e-03,  2.76190673e-03,
        -1.25535223e-03, -1.63318954e-03,  2.86500196e-03,  1.83295061e-03,
         8.75759004e-04,  1.12937520e-03, -3.11822931e-03,  2.10953801e-03,
        -7.97503387e-04, -2.14091585e-04,  3.54559918e-03,  1.64235055e-05,
        -2.80381448e-03, -6.44624299e-04,  3.26027984e-03,  1.21130580e-03,
        -4.21148484e-04,  1.16103169e-03, -2.77393734e-03,  3.31877769e-03,
        -2.69837250e-03,  2.00184548e-04,  1.64796291e-06,  1.93977251e-03,
        -2.24720268e-03, -2.47343118e-03, -3.34594352e-03, -4.67102981e-04,
         3.16408879e-03, -3.42374966e-03, -3.78200002e-04, -1.12467166e-03,
         8.72244088e-04,  2.93626837e-03, -8.01896078e-04, -1.01761882e-03,
         1.68931645e-03,  1.07581639e-03, -8.72513016e-04, -4.81796453e-04,
        -6.63497762e-04,  2.93643095e-03,  1.84886851e-03, -2.54873667e-03,
        -8.31038852e-04,  1.45162888e-03, -5.74819219e-03, -5.57222548e-04,
         2.70829332e-04,  1.99307142e-03, -7.87319307e-04,  1.48728676e-03,
        -9.63227901e-04, -2.69680330e-03, -7.93800541e-04, -2.95544759e-03,
         8.77227220e-08,  1.28951904e-03,  2.74594750e-03, -1.82896916e-03,
        -9.46138685e-04, -2.09329126e-04,  6.52025745e-04, -2.46554988e-04,
         3.13350374e-03,  1.74097802e-04, -3.91854432e-04,  1.55388987e-03,
         1.26388272e-03, -7.54080928e-04, -1.77274434e-05, -2.12289426e-03,
        -2.00352297e-03,  1.06394036e-03, -4.51731371e-03,  1.19525765e-03,
         2.49070087e-03,  1.83486299e-03, -1.85852392e-03,  2.04561213e-03,
         2.48912671e-04,  3.62297530e-03, -3.84824293e-04, -1.81903035e-04,
         4.15395592e-04,  1.41442940e-03, -1.82413014e-04,  3.14432695e-03,
         2.26562101e-03,  1.62919878e-03, -2.00885226e-03, -6.82412611e-04,
        -7.72573363e-04, -2.69601268e-03, -2.16525221e-03,  4.66719811e-03,
         1.07136421e-03,  4.83403148e-04, -1.34669858e-03, -1.00973825e-03,
        -1.15796779e-03,  7.78107478e-03,  2.00045790e-03, -1.78168947e-03,
         1.96177997e-03, -3.82799499e-03,  1.31742998e-03, -3.21324405e-04,
        -6.28928667e-04,  8.67202910e-04, -1.34431691e-03,  4.15956501e-04,
        -2.35896572e-03, -8.42041235e-04,  2.06638194e-03,  1.85457413e-03,
        -5.18000691e-04,  2.78187895e-03, -3.47831739e-04, -4.04857332e-04,
        -9.92191059e-05, -8.58510000e-04,  3.28009529e-03, -5.55587758e-04,
        -5.12623428e-04, -5.16492017e-04, -3.68095493e-03,  3.70705334e-03,
        -3.31006324e-04, -8.59396478e-04,  3.21049274e-04,  1.81434604e-03,
         1.53945952e-03,  2.47209693e-03, -2.37377821e-03,  3.41406703e-03,
         6.84064878e-04,  1.82175902e-03, -1.90755713e-03,  3.98237026e-03,
        -4.58644883e-04, -1.09977609e-03, -8.94096785e-04,  8.03617333e-04,
         4.85011443e-04, -1.03448859e-03, -3.07792862e-03,  1.26252249e-04,
         1.69157351e-03,  2.61123642e-03, -3.19704563e-03,  2.43606691e-03,
        -2.26203259e-03, -1.20970551e-03, -1.50428680e-03,  5.78581310e-04,
         1.55047427e-03, -2.64021594e-03, -7.17034572e-04, -1.25670470e-03,
         2.49983086e-03, -3.12033688e-03,  9.89496735e-04,  2.58583530e-03,
        -1.00530330e-03, -1.90420250e-03, -1.37745843e-04,  8.46054608e-04,
        -1.45632200e-03, -8.99663158e-04,  4.23651804e-04,  4.89212517e-04,
        -1.74793644e-03, -5.88769342e-05, -2.82431581e-03,  1.15487480e-03,
        -4.19629750e-03, -4.61990766e-04, -2.24425439e-03,  1.67657116e-03,
        -5.01498698e-04, -4.41904958e-04,  8.26182507e-04,  1.35744434e-05,
        -3.96107796e-03,  1.19389475e-03,  1.18641122e-03, -2.15513028e-03,
         7.57563209e-04,  1.32917012e-04, -2.25337547e-04, -4.10774653e-04,
         5.55188294e-05, -1.41482344e-03,  4.71510812e-03, -7.88552457e-04,
        -1.17799894e-03,  2.68427246e-04,  1.62826879e-03,  6.10886812e-04,
         4.99154348e-03, -7.02734137e-04, -2.13349444e-03,  1.45154131e-04,
        -2.58699795e-05, -1.10281379e-03,  1.64648523e-03, -2.50384076e-03,
        -2.03781120e-03,  2.35459552e-03, -1.09812160e-03, -1.12972209e-04,
         4.15924866e-03, -1.53816411e-04, -5.36880286e-04,  3.20186392e-04,
         2.07007515e-03, -4.25033336e-04, -4.75710780e-03, -3.25001225e-03,
         2.13800539e-03, -2.76952199e-03, -2.14067354e-03, -8.40289958e-05,
         3.68478030e-03, -1.75140073e-04, -7.80251184e-04,  3.92400156e-03,
        -1.55528583e-03,  1.93265429e-03, -7.19201292e-04,  5.57863107e-04,
         1.14033645e-03, -1.89739575e-03,  1.42102774e-03, -1.61547730e-03,
        -1.07491706e-03, -1.38147407e-03, -5.41361961e-04, -5.18379606e-03,
        -3.72735123e-03,  1.80195873e-04, -1.58796103e-03, -3.31388523e-03,
         4.98104251e-03, -4.81937417e-04, -1.25446572e-03,  1.24657113e-03,
        -8.49832327e-04,  3.06848026e-04,  7.62986238e-04, -1.99047497e-03,
         5.33504358e-04, -7.12992200e-04, -6.59387773e-04, -1.87723903e-03,
         1.67231866e-03, -6.81178567e-04, -3.26525483e-04, -6.85468405e-03,
        -3.92626468e-03,  1.87839532e-03, -1.76158506e-03,  2.32388213e-03,
         1.30376782e-03,  1.60038207e-03, -2.26909720e-04, -4.57323837e-03,
        -1.09445376e-03,  9.64228670e-04,  3.65994857e-03, -4.67166719e-03,
        -1.68790593e-04,  1.07677986e-03,  2.30246208e-04, -9.72424089e-04,
        -3.62821359e-04, -2.66679957e-03,  8.34445827e-04, -6.16440462e-04,
        -3.31309383e-04, -1.55251128e-03, -1.59167059e-04, -2.36868218e-03,
        -1.20404901e-03, -5.82238032e-04,  1.69468155e-03, -1.43839627e-03,
         6.99541982e-04,  1.79142550e-03, -1.91818668e-03,  2.88510741e-03,
         9.48641218e-04,  1.80268953e-03, -3.93947927e-04,  4.32119058e-03,
        -3.08109221e-03, -2.46757156e-03,  5.86965264e-04, -1.08924329e-04,
        -2.41127658e-03, -2.95970492e-04, -1.79995319e-03,  1.45830794e-03,
         1.33153379e-04,  1.57145778e-04, -4.81571795e-03,  3.62612488e-03,
        -4.20611983e-04, -1.26861768e-04,  3.86321140e-04, -3.65170488e-03,
         1.17336710e-03, -2.67088652e-03, -5.99898642e-04, -1.69045504e-03,
         1.03590467e-03, -2.50724019e-03, -2.57722413e-03,  2.76545579e-03,
        -4.28718430e-03,  2.08064410e-03,  1.69272019e-03, -1.00838143e-03,
         1.71932606e-03, -1.78350192e-03,  3.02738400e-03, -7.96355315e-04,
         2.33708528e-04,  9.24474904e-04,  2.13997269e-03,  8.60802242e-04,
        -1.25946863e-03,  4.54673883e-04, -1.70756314e-03,  1.65637621e-03,
         1.35861991e-03, -7.53135717e-04,  3.74156454e-03, -6.26859939e-03,
        -1.95780911e-04,  2.07589603e-03, -1.26310627e-03, -9.37016204e-04,
         8.82585975e-04, -8.62121754e-04, -2.98455808e-03,  5.63556789e-04,
         2.41258517e-03, -2.06757041e-03,  6.07399821e-04,  3.00855008e-03,
        -1.30791224e-03,  7.00637711e-04,  1.40569877e-03,  9.30478772e-04,
        -1.10041813e-03,  1.06800495e-03, -1.32047394e-03,  1.60718838e-03,
         1.66222536e-03, -9.29214792e-04,  1.54284109e-03, -1.00820647e-03,
        -3.78010445e-04,  8.99361084e-05,  2.24415894e-03,  3.07011958e-04,
         1.62761741e-03, -1.83090104e-04, -2.70767918e-03,  2.67512581e-03,
        -1.12147057e-03, -1.45449558e-03, -1.18675736e-03,  2.24007348e-03,
         2.44561177e-03,  1.73268716e-03,  1.11228479e-03, -4.62114004e-03,
         1.69695565e-04, -1.20397654e-03, -2.29517712e-03,  1.17750316e-03,
        -2.78485167e-03, -2.09350953e-03, -6.00478111e-04, -1.40653595e-04,
         2.14100488e-03,  2.34799801e-04, -1.30156311e-03,  3.56092949e-03,
         3.91778729e-03, -1.15544970e-03,  8.37869777e-04, -1.09286111e-03,
         5.48842669e-03, -2.47402195e-04, -1.37378991e-03,  4.37937670e-04,
        -4.76261747e-03, -4.05984015e-03,  1.60102568e-03, -1.60749021e-03,
        -2.83045083e-03,  1.60767155e-04,  2.48828461e-03,  1.23105911e-03,
        -1.23149367e-03,  1.30051567e-03,  1.52932029e-03,  4.73920766e-06,
        -2.53804323e-03, -3.48382863e-03, -2.52849001e-03,  4.65440538e-03,
        -1.27642502e-03, -2.91615810e-03,  3.30642166e-04,  5.01060481e-03,
        -1.11300095e-03,  1.66758910e-03,  3.99573710e-04, -1.77625150e-03,
        -3.49842616e-04,  2.45969299e-03, -7.85786792e-05, -1.32534786e-03,
         3.70529270e-04, -4.30308837e-04,  2.02441429e-03,  1.14151959e-03,
         3.77073807e-04, -1.52724032e-03,  4.89098702e-03, -2.10060041e-03,
        -1.45826473e-03,  9.12612335e-04, -1.42609644e-03, -4.25122867e-04,
         1.03863925e-03,  5.94739513e-04, -6.07514774e-04, -1.14085321e-03,
        -3.86665628e-03, -1.50845052e-03,  1.96071190e-03, -1.92119372e-03,
         3.90793091e-03, -3.40341296e-04,  5.67021123e-04,  3.24016218e-03,
        -1.16087382e-03,  1.49011686e-03, -2.06584714e-03, -6.95056919e-04,
         7.35607631e-04, -2.92164903e-03,  2.51872360e-03, -2.61559287e-03,
         5.12617881e-05, -4.37874640e-03,  1.35471140e-03,  1.17753277e-03,
         1.53653253e-03,  4.11965027e-03, -2.47459485e-03, -1.51721868e-04,
        -4.29739783e-03,  5.59187858e-04, -5.12399334e-03, -1.03949260e-03,
        -2.52684296e-03, -5.23612926e-04,  2.56514911e-03,  1.67862602e-03,
         2.45222532e-03,  2.14640498e-03,  1.65229671e-03,  4.84759310e-04,
        -1.02454754e-03, -2.33616780e-03, -1.85147180e-03,  2.06660782e-03,
         8.77384394e-04, -9.22478458e-04, -4.54804422e-03,  2.32694563e-03,
         1.48134737e-03,  9.18565693e-04, -1.09765581e-03, -9.21129929e-04,
         9.67454223e-04,  1.52581975e-03,  4.67470656e-04,  1.23737933e-03,
        -3.97584373e-04,  4.84837202e-04,  9.58707083e-04, -4.40738164e-04,
         1.66078227e-03, -9.48012800e-04,  1.48094360e-04,  2.31940054e-03,
        -1.23059977e-03,  5.97460216e-05,  9.93103428e-04,  5.22985223e-04,
         9.08906717e-04, -3.05086790e-03, -1.93428433e-03,  1.45134653e-03,
        -2.38313274e-03, -1.49264371e-03, -1.67223887e-03,  5.39745264e-04,
        -1.33539043e-04,  6.19911791e-03, -2.60759298e-04,  9.93866802e-04,
        -3.51821379e-04,  4.19972428e-03, -9.97510700e-05, -1.81083637e-03,
        -1.64502644e-04,  3.10701082e-03, -5.67427109e-04, -2.25300154e-03,
         1.85494005e-03,  1.39448436e-04,  3.33653987e-03,  5.83478371e-04,
         1.36537433e-03, -4.22676100e-03, -7.05047203e-04,  2.59254925e-04,
         8.07336457e-04, -1.39153803e-03, -2.02513634e-03, -2.56151806e-03,
        -1.59395276e-03, -3.74393446e-03,  3.17534782e-04,  1.45077471e-03,
         4.31960949e-03,  8.04939837e-04, -3.40902821e-03,  5.07794969e-03,
        -1.73576999e-03,  7.07782333e-04,  1.95444360e-04,  2.48101505e-04,
        -1.17093537e-03,  1.16696396e-03,  9.56478459e-04, -1.47379684e-03,
        -3.46084830e-03,  1.69210608e-03,  1.13321645e-04,  1.54552408e-03,
        -1.48533843e-03, -2.45136173e-03, -8.41747179e-04,  1.56201875e-03,
         1.18577698e-03, -2.68406244e-03, -1.34682400e-03,  9.93731499e-04,
        -7.84119020e-04, -6.30757907e-03, -8.83622391e-04, -1.75370698e-03,
         4.06104312e-03, -2.06468985e-03, -2.88008401e-03, -3.05809445e-03,
        -3.37199412e-04,  4.95670677e-04, -2.04052902e-03,  2.16533192e-03,
         8.89923557e-04, -5.57732411e-04,  1.69921519e-03, -1.00811372e-03,
        -2.99395347e-03, -4.81172022e-04,  3.86822913e-03,  1.29629048e-03,
         3.68009551e-04, -1.38617154e-03,  2.85482091e-03,  6.44714738e-04,
        -1.04165265e-03,  3.04624608e-05,  1.49241182e-03, -1.61313645e-03,
        -9.11687602e-04,  2.58525936e-03,  1.78344503e-03,  1.36942002e-04,
         1.38337252e-03, -3.37337066e-04, -1.09224510e-04,  2.67310668e-04,
         3.84381289e-03, -1.73598096e-03,  2.08315698e-04, -2.37945943e-03,
        -1.27456233e-03, -6.53889471e-03,  1.69450468e-03, -7.06813850e-04,
         7.89604809e-04,  4.22629552e-04, -4.92881589e-04, -1.96159766e-03,
         4.95160238e-05,  9.17064366e-04,  1.17756154e-03,  1.65127280e-03,
         7.58075469e-04,  3.05011558e-04,  3.18247864e-03,  1.96826720e-03,
         1.60312891e-03, -1.13757712e-03,  1.38759875e-04, -3.52625946e-04,
         7.79369973e-03, -1.62534273e-03,  4.85490106e-04, -1.91983700e-04,
         1.81964910e-04, -1.23270842e-03,  2.36103409e-03,  6.15467658e-04,
        -9.80857750e-04,  2.77759503e-04, -1.84710032e-03, -8.88731296e-04,
         4.25976661e-03, -9.49424466e-04, -1.85132985e-03,  1.05869003e-03,
         3.46103899e-03, -4.11338051e-03, -4.94720861e-04, -2.58122459e-03,
        -1.30557636e-03,  2.48829541e-03, -7.38764917e-04,  3.36941071e-04,
         8.38828394e-05, -3.62730911e-04,  1.00910052e-03,  3.03941929e-03,
        -1.90216953e-04, -6.75457064e-04, -1.73411687e-03,  7.55784763e-04,
         7.24495463e-04,  9.16901541e-04, -4.77118878e-04, -2.45321899e-03,
        -2.88131831e-03,  9.97793080e-04,  2.68699862e-03, -7.31924100e-04,
        -1.93041866e-03,  1.71633859e-03, -1.27484384e-03,  2.02746035e-04,
        -8.11362282e-04,  2.24654005e-03,  1.95286335e-03,  5.24754928e-03,
        -1.39608743e-03,  3.55537897e-04, -2.02600952e-03,  1.88942094e-03,
         1.31815602e-03,  2.92237486e-03, -7.43558880e-04, -4.18585821e-04,
         3.43381531e-03, -9.54198310e-04, -2.27038777e-03, -2.79014287e-03,
         2.23852136e-03,  2.63248327e-03,  3.53149630e-04,  1.35024500e-03,
         5.87813964e-04,  2.63815115e-03,  9.15729958e-05, -1.88123999e-04,
         1.04484792e-03,  2.81390362e-03, -9.96146111e-05, -1.78360614e-03,
        -2.53610300e-04,  2.68870936e-03, -5.47299015e-04, -8.20300378e-04,
        -6.64525969e-04, -2.78720498e-03,  2.28273014e-03,  1.93138737e-03,
         6.59563561e-05, -6.28931365e-03, -1.42960854e-03, -9.26635119e-04,
        -1.17799522e-03, -1.12097789e-03, -1.62824136e-03,  1.03368726e-03,
        -1.27316021e-03, -4.77519915e-03, -1.42560175e-03, -3.03115370e-03,
         6.88159138e-04,  6.16931500e-04,  1.13280218e-03, -2.41878318e-04,
         1.10843669e-03,  1.33886710e-03, -7.49356543e-04,  2.12894851e-03,
        -1.94104673e-03, -5.95742885e-04,  3.86657036e-04, -3.11624137e-03,
        -1.63124963e-03, -2.27594269e-04, -1.63450192e-03,  2.46972933e-03,
        -4.88320969e-04,  1.03821185e-03, -2.95757858e-04,  1.16894141e-03,
         2.24556193e-03, -1.01201556e-04, -1.58104998e-03, -6.95448503e-04,
         1.00772400e-03,  2.18111723e-03, -1.73621386e-03,  3.88613865e-03,
         9.95758313e-04, -2.22442359e-03, -1.64242820e-04,  4.51490991e-03,
        -2.09562199e-04,  4.87428035e-04, -2.00781910e-03,  6.02548352e-04,
         4.70561592e-04,  4.74250625e-04, -4.45888890e-04, -1.29528620e-03,
        -8.73190919e-04, -1.48509191e-06,  2.25357615e-03, -5.24395727e-03,
        -3.56435997e-03, -3.09707122e-03, -2.65268251e-03,  2.96937724e-03,
         6.05451984e-04, -5.08121548e-03, -1.82409130e-03,  6.12190104e-03,
        -1.29369443e-03, -1.53273137e-03,  3.56396594e-04, -7.57611716e-04,
         1.27874740e-03, -8.50988830e-04,  2.01758366e-03, -1.70917463e-03,
        -5.56471145e-03, -1.77108373e-03,  1.22711897e-04, -2.17179725e-03,
         9.06779006e-04,  4.03157731e-04, -2.64712063e-04, -7.90149670e-04,
         9.32166748e-04, -6.86646929e-04,  3.83870548e-03, -3.79712915e-03,
         5.48096606e-04,  1.19762294e-03,  5.25236154e-04,  1.67310754e-03,
        -2.27761408e-03, -1.06840561e-04, -7.51978921e-04, -3.39893109e-03,
        -7.02626443e-04,  1.12274852e-03, -2.10196608e-03, -3.34205338e-04,
         8.28522592e-04, -2.90471989e-03,  1.04367456e-04,  9.65263424e-04,
        -2.49622226e-03,  1.51991087e-03,  1.78185591e-03,  3.56524604e-03,
        -1.56616696e-03,  2.85525396e-03,  5.27371053e-04, -1.49663871e-03,
        -3.15516767e-04, -4.35424120e-03, -1.42441941e-03, -1.25684826e-03,
         4.58457438e-03,  1.81027991e-04, -2.03923211e-03, -5.82669011e-03,
         2.63304516e-03,  1.21299117e-04, -1.63381273e-03, -1.84835618e-03,
         3.54280110e-04, -1.36364702e-03, -2.89614597e-03,  6.08591086e-04,
         2.01539852e-04, -1.25540830e-03, -1.33031132e-04, -2.87480802e-04,
        -2.08371528e-03, -1.14740993e-03, -1.09791518e-03,  1.00183975e-03,
         1.11673928e-03,  1.76678753e-03,  1.46460960e-04,  4.01847643e-03,
         1.39586556e-04,  1.47430571e-03,  1.98331715e-03, -1.19336592e-03,
        -2.25338046e-03,  2.68553840e-03,  3.36280148e-03,  1.33117975e-03,
        -2.41757452e-03,  2.92181507e-03, -1.01397202e-03,  1.07889638e-03,
         1.65012242e-04,  3.63345976e-04, -2.34998926e-03,  2.60806835e-03,
        -1.91079207e-03,  2.34946195e-04, -5.10727424e-04, -4.60314745e-04,
        -3.92666895e-03, -2.17261255e-03, -2.23369856e-03, -2.42589194e-03,
        -1.72471128e-03, -5.00030835e-04,  9.55906992e-04,  1.30439996e-03,
         1.08742270e-03, -1.26341634e-03, -4.84305563e-03,  1.05385868e-03,
        -2.62342112e-04, -9.57477880e-04, -2.28162109e-03, -8.28989925e-04,
        -2.15194447e-03, -7.66486879e-04,  4.09758250e-04, -6.67421288e-04,
        -9.76297903e-04, -2.15801201e-03, -1.94073563e-03, -8.12550850e-04,
         5.76150473e-04, -1.37118459e-03,  1.46912831e-03, -2.19988467e-03,
         1.44039419e-03, -1.01378992e-03, -2.96580298e-03, -1.09746894e-04,
         8.61276970e-04, -5.90466852e-05, -1.29624548e-03, -2.73859226e-03,
        -2.00627839e-03, -2.79292186e-03, -7.69326240e-05,  9.61198761e-04,
        -5.35474606e-04, -1.81158266e-03, -3.57326460e-03, -4.23277005e-04,
         4.77073318e-04,  4.43622033e-04, -4.52977935e-04,  9.15632084e-04,
        -9.78223632e-04,  1.75782747e-03,  1.48599569e-04,  1.72949739e-03,
        -1.43702252e-03,  5.39244168e-05, -1.95234072e-05, -4.02814215e-04,
         1.35260621e-04, -3.12376891e-03, -3.19333284e-03, -5.43444284e-04,
         2.89410324e-03,  2.58221773e-04,  1.27017599e-03,  1.83806665e-03,
        -4.83885071e-03,  3.23368277e-03,  3.16166100e-03,  4.78720875e-03,
         5.60256797e-04, -1.22136985e-03,  2.87697757e-04, -1.25943171e-04,
        -1.23053957e-04, -7.43075679e-04, -9.72336191e-04,  1.84850105e-03,
        -4.07834528e-04,  3.61510653e-04,  7.86428681e-04,  4.78907778e-04,
         2.17424373e-04,  6.30597482e-04, -1.52582753e-03,  2.37936728e-03,
        -6.59873760e-04,  1.97681071e-03, -2.86263010e-03,  2.13073006e-03,
         1.67887140e-03, -5.78881252e-04, -7.55461240e-05,  4.43178938e-03,
        -9.88006765e-04, -3.40497762e-04, -1.61988548e-04, -4.76631331e-04,
         2.25756435e-03,  2.10452809e-03,  3.60171984e-03, -7.31828852e-04,
        -1.85513276e-03,  5.98106777e-03, -8.16297650e-05,  1.85509865e-03,
         7.41527319e-03, -1.77944355e-03, -1.35450193e-03, -3.34910935e-05])}

In [38]:
import plotly.express as px
fig = px.histogram(x=result["random_scores"],nbins=50,title="Permutation Distribution of Lead Score")
fig.add_vline(x=result["real_score"],line_width=3)
fig.show()

In [4]:
from pathlib import Path
import pandas as pd
import numpy as np

DATA_DIR = Path("../data/backtest_1min_with_warmup_by_symbol")

def load_symbol_returns(symbol, data_dir=DATA_DIR):
    path = data_dir / f"{symbol}_backtest_1min_warmup.parquet"
    
    df = pd.read_parquet(path)
    df = df[["date", "close"]].copy()
    df["log_return"] = np.log(df["close"] / df["close"].shift(1))
    
    return df[["date", "log_return"]].dropna()


# Cargar retornos solo de los símbolos que aparecen en df_candidate_pairs
symbols = sorted(
    set(df_candidate_pairs["stock_a"])
    .union(set(df_candidate_pairs["stock_b"]))
)

returns_by_symbol = {}

for symbol in symbols:
    returns_by_symbol[symbol] = load_symbol_returns(symbol)

len(returns_by_symbol)

62

In [12]:
def lead_score(x, y, lag=1):
    a_to_b = x.corr(y.shift(-lag))
    b_to_a = y.corr(x.shift(-lag))
    return a_to_b - b_to_a


def permutation_test_lead_score(
    x,
    y,
    lag=1,
    n_permutations=1000,
    random_state=42
):
    rng = np.random.default_rng(random_state)

    real_score = lead_score(x, y, lag)

    random_scores = []

    y_clean = y.dropna()
    x_aligned = x.loc[y_clean.index]

    for _ in range(n_permutations):
        y_perm = rng.permutation(y_clean.values)

        y_perm = pd.Series(
            y_perm,
            index=y_clean.index
        )

        score = lead_score(x_aligned, y_perm, lag)
        random_scores.append(score)

    random_scores = np.array(random_scores)

    p_value = np.mean(
        np.abs(random_scores) >= np.abs(real_score)
    )

    return {
        "lead_score": real_score,
        "random_mean": random_scores.mean(),
        "random_std": random_scores.std(),
        "p_value": p_value
    }


MIN_OBS = 10000
N_PERMUTATIONS = 1000
LAG = 1

all_tests = []

for _, row in df_candidate_pairs.head(40).iterrows():

    stock_a = row["stock_a"]
    stock_b = row["stock_b"]
    sector = row["sector"]

    a = returns_by_symbol[stock_a].rename(columns={"log_return": "r_a"})
    b = returns_by_symbol[stock_b].rename(columns={"log_return": "r_b"})

    pair_df = pd.merge(
        a,
        b,
        on="date",
        how="inner"
    ).dropna()

    n_obs = len(pair_df)

    if n_obs < MIN_OBS:
        print(f"Skipping {stock_a}-{stock_b}: only {n_obs} observations")
        continue

    test = permutation_test_lead_score(
        pair_df["r_a"],
        pair_df["r_b"],
        lag=LAG,
        n_permutations=N_PERMUTATIONS,
        random_state=42
    )

    lead_score_value = test["lead_score"]

    all_tests.append({
        "pair": f"{stock_a}-{stock_b}",
        "stock_a": stock_a,
        "stock_b": stock_b,
        "sector": sector,
        "lag": LAG,
        "lead_score": lead_score_value,
        "abs_lead_score": abs(lead_score_value),
        "p_value": test["p_value"],
        "random_mean": test["random_mean"],
        "random_std": test["random_std"],
        "empirical_leader": stock_a if lead_score_value > 0 else stock_b,
        "empirical_follower": stock_b if lead_score_value > 0 else stock_a,
        "n_obs": n_obs
    })

lead_lag_significance = pd.DataFrame(all_tests)

lead_lag_significance.sort_values("p_value").head(20)

Skipping COST-WMT: only 5683 observations

,pair,stock_a,stock_b,sector,lag,lead_score,abs_lead_score,p_value,random_mean,random_std,empirical_leader,empirical_follower,n_obs
0,CCEP-KDP,CCEP,KDP,BEVERAGES,1,-0.017671,0.017671,0.0,-0.000032,0.002375,KDP,CCEP,315461
1,CCEP-PEP,CCEP,PEP,BEVERAGES,1,-0.027135,0.027135,0.0,0.000017,0.002475,PEP,CCEP,315461
2,KDP-PEP,KDP,PEP,BEVERAGES,1,-0.009183,0.009183,0.0,-0.000020,0.002031,PEP,KDP,477455
3,AMGN-GILD,AMGN,GILD,"BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)",1,-0.021105,0.021105,0.0,-0.000020,0.001951,GILD,AMGN,477455
4,CHTR-CMCSA,CHTR,CMCSA,CABLE & OTHER PAY TELEVISION SERVICES,1,-0.043587,0.043587,0.0,-0.000013,0.002097,CMCSA,CHTR,477455
14,REGN-VRTX,REGN,VRTX,PHARMACEUTICAL PREPARATIONS,1,-0.031920,0.031920,0.0,0.000036,0.001955,VRTX,REGN,477455
11,ALNY-VRTX,ALNY,VRTX,PHARMACEUTICAL PREPARATIONS,1,-0.026512,0.026512,0.0,-0.000119,0.003241,VRTX,ALNY,172143
8,PCAR-TSLA,PCAR,TSLA,MOTOR VEHICLES & PASSENGER CAR BODIES,1,-0.008360,0.008360,0.0,-0.000024,0.002049,TSLA,PCAR,477455
24,ADI-MU,ADI,MU,SEMICONDUCTORS & RELATED DEVICES,1,-0.014484,0.014484,0.0,-0.000068,0.002054,MU,ADI,477455
25,ADI-NVDA,ADI,NVDA,SEMICONDUCTORS & RELATED DEVICES,1,-0.017401,0.017401,0.0,-0.000070,0.001989,NVDA,ADI,477455
21,ADI-MCHP,ADI,MCHP,SEMICONDUCTORS & RELATED DEVICES,1,-0.011294,0.011294,0.0,-0.000066,0.001951,MCHP,ADI,477455
23,ADI-MRVL,ADI,MRVL,SEMICONDUCTORS & RELATED DEVICES,1,-0.015627,0.015627,0.0,-0.000024,0.001896,MRVL,ADI,477455
20,ADI-INTC,ADI,INTC,SEMICONDUCTORS & RELATED DEVICES,1,-0.015827,0.015827,0.0,-0.000024,0.001945,INTC,ADI,477455
18,ADI-ASML,ADI,ASML,SEMICONDUCTORS & RELATED DEVICES,1,0.028947,0.028947,0.0,-0.000018,0.001933,ADI,ASML,477455
17,ADI-AMD,ADI,AMD,SEMICONDUCTORS & RELATED DEVICES,1,-0.014571,0.014571,0.0,-0.000033,0.001943,AMD,ADI,477455
16,ADI-AMAT,ADI,AMAT,SEMICONDUCTORS & RELATED DEVICES,1,-0.015920,0.015920,0.0,-0.000017,0.001995,AMAT,ADI,477455
28,AMAT-AMD,AMAT,AMD,SEMICONDUCTORS & RELATED DEVICES,1,-0.009073,0.009073,0.0,-0.000054,0.001955,AMD,AMAT,477455
29,AMAT-ASML,AMAT,ASML,SEMICONDUCTORS & RELATED DEVICES,1,0.042287,0.042287,0.0,0.000016,0.002000,AMAT,ASML,477455
26,ADI-NXPI,ADI,NXPI,SEMICONDUCTORS & RELATED DEVICES,1,0.020356,0.020356,0.0,0.000021,0.002001,ADI,NXPI,477455
27,ADI-TXN,ADI,TXN,SEMICONDUCTORS & RELATED DEVICES,1,-0.011913,0.011913,0.0,0.000020,0.001984,TXN,ADI,477455

In [13]:
import plotly.express as px

fig = px.scatter(
    lead_lag_significance,
    x="abs_lead_score",
    y="p_value",
    hover_data=["pair","sector"],
    title="Lead Score vs Statistical Significance"
)

fig.add_hline(
    y=0.05,
    line_dash="dash"
)

fig.show()

In [14]:
lead_lag_significance.groupby("empirical_leader").size().sort_values(ascending=False)

empirical_leader
AMAT     7
ADI      4
AMD      2
INSM     2
INTC     2
VRTX     2
REGN     2
MRVL     2
MU       2
PEP      2
NVDA     2
EXC      1
CMCSA    1
KDP      1
MCHP     1
GILD     1
FTNT     1
PDD      1
STX      1
TSLA     1
TXN      1
dtype: int64

Hasta ahora encontramos:

- La señal vive principalmente en lag=1.
- Algunos pares no tienen efecto significativo.
- Otros pares sí tienen lead_score muy por encima de lo esperado bajo permutación.
-El líder empírico no necesariamente coincide con una narrativa simple de market cap.
- ADI, por ejemplo, aparece muchas veces como follower frente a AMD, AMAT, INTC, MRVL, MU, NVDA, TXN.

# ¿Qué tan buena era la regla de market cap para identificar al líder?

In [18]:
from pathlib import Path
import pandas as pd
import numpy as np

DATA_DIR = Path("../data/backtest_1min_with_warmup_by_symbol")

def get_market_cap(symbol, data_dir=DATA_DIR):
    path = data_dir / f"{symbol}_backtest_1min_warmup.parquet"
    df = pd.read_parquet(path, columns=["market_cap"])
    return df["market_cap"].dropna().iloc[0]


def get_market_cap_leader(stock_a, stock_b):
    market_cap_a = get_market_cap(stock_a)
    market_cap_b = get_market_cap(stock_b)

    if market_cap_a >= market_cap_b:
        return stock_a, stock_b, market_cap_a, market_cap_b
    else:
        return stock_b, stock_a, market_cap_a, market_cap_b


rows = []

for _, row in lead_lag_significance.iterrows():

    stock_a = row["stock_a"]
    stock_b = row["stock_b"]

    market_cap_leader, market_cap_follower, market_cap_a, market_cap_b = get_market_cap_leader(
        stock_a,
        stock_b
    )

    rows.append({
        "pair": row["pair"],
        "stock_a": stock_a,
        "stock_b": stock_b,
        "sector": row["sector"],
        "lag": row["lag"],
        "lead_score": row["lead_score"],
        "abs_lead_score": row["abs_lead_score"],
        "p_value": row["p_value"],
        "empirical_leader": row["empirical_leader"],
        "empirical_follower": row["empirical_follower"],
        "market_cap_leader": market_cap_leader,
        "market_cap_follower": market_cap_follower,
        "market_cap_a": market_cap_a,
        "market_cap_b": market_cap_b,
        "leader_match": row["empirical_leader"] == market_cap_leader,
        "n_obs": row["n_obs"]
    })

leader_comparison = pd.DataFrame(rows)

leader_comparison.head()

,pair,stock_a,stock_b,sector,lag,lead_score,abs_lead_score,p_value,empirical_leader,empirical_follower,market_cap_leader,market_cap_follower,market_cap_a,market_cap_b,leader_match,n_obs
0,CCEP-KDP,CCEP,KDP,BEVERAGES,1,-0.017671,0.017671,0.0,KDP,CCEP,CCEP,KDP,4.254597e+10,3.865169e+10,False,315461
1,CCEP-PEP,CCEP,PEP,BEVERAGES,1,-0.027135,0.027135,0.0,PEP,CCEP,PEP,CCEP,4.254597e+10,2.271097e+11,True,315461
2,KDP-PEP,KDP,PEP,BEVERAGES,1,-0.009183,0.009183,0.0,PEP,KDP,PEP,KDP,3.865169e+10,2.271097e+11,True,477455
3,AMGN-GILD,AMGN,GILD,"BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)",1,-0.021105,0.021105,0.0,GILD,AMGN,AMGN,GILD,1.973818e+11,1.814246e+11,False,477455
4,CHTR-CMCSA,CHTR,CMCSA,CABLE & OTHER PAY TELEVISION SERVICES,1,-0.043587,0.043587,0.0,CMCSA,CHTR,CMCSA,CHTR,2.838826e+10,1.097343e+11,True,477455

In [19]:
leader_comparison["leader_match"].mean()

np.float64(0.6153846153846154)

In [20]:
leader_comparison.query("p_value < 0.05")["leader_match"].mean()

np.float64(0.6785714285714286)

El liderazgo basado en market capitalization no es arbitrario. Aproximadamente 68% de los pares con evidencia estadística de lead-lag presentan coincidencia entre el líder empírico y el líder definido por market capitalization. Esto sugiere que market cap captura una parte importante del proceso de difusión de información, aunque existe una fracción relevante de pares (~32%) donde el liderazgo observado difiere del esperado, abriendo la posibilidad de construir reglas de selección más informativas que la simple jerarquía por tamaño.