In [4]:
import plotly.io as pio
pio.renderers.default = "notebook_connected+png" 

from IPython.display import Image, display
import sys
import os
# Add project root to path
sys.path.append(os.path.abspath(".."))
# libs 
import numpy as np
import plotly.graph_objects as go
import requests
import pandas as pd
import ast
import time

# import data market from polymarket 
from src.analytics.download_data import safe_parse_list, fetch_many_markets, filter_fed_rates_markets, extract_yes_token_id, get_price_history

In [5]:
# 1. Download closed markets

df_markets_raw = fetch_many_markets(
    max_pages=10,
    limit=500,
    closed=True
)

print("Total markets downloaded:", len(df_markets_raw))

# 2. Filter Fed / rates markets


df_fed = filter_fed_rates_markets(df_markets_raw)

df_fed["yes_token_id"] = df_fed.apply(extract_yes_token_id, axis=1)

cols_to_keep = [
    "id",
    "question",
    "slug",
    "category",
    "endDate",
    "closed",
    "volume",
    "liquidity",
    "outcomes",
    "outcomePrices",
    "clobTokenIds",
    "yes_token_id"
]

cols_to_keep = [c for c in cols_to_keep if c in df_fed.columns]

df_fed = df_fed[cols_to_keep].dropna(subset=["yes_token_id"])

print("Fed/rates markets found:", len(df_fed))

display(df_fed.head())



# 3. Download price history
all_histories = []

for _, row in df_fed.iterrows():
    token_id = row["yes_token_id"]

    try:
        hist = get_price_history(
            clob_token_id=token_id,
            fidelity_minutes=60
        )

        if len(hist) > 0:
            hist["market_id"] = row["id"]
            hist["question"] = row.get("question", None)
            hist["slug"] = row.get("slug", None)
            all_histories.append(hist)

        time.sleep(0.25)

    except Exception as e:
        print(f"Error for market {row.get('id')}: {e}")


df_prices = pd.concat(all_histories, ignore_index=True) if all_histories else pd.DataFrame()

print("Price history rows:", len(df_prices))

display(df_prices.head())

Total markets downloaded: 1000
Fed/rates markets found: 70

,id,question,slug,category,endDate,closed,volume,liquidity,outcomes,outcomePrices,clobTokenIds,yes_token_id
14,57,Will Dharma’s Phase 1 Retroactive UNI Distribu...,will-dharma-s-phase-1-retroactive-uni-distribu...,Crypto,2020-10-31T00:00:00Z,True,35661.941003,0,"[""Yes"", ""No""]","[""0"", ""0""]","[""72218237979282777228049705424647682506448885...",7221823797928277722804970542464768250644888572...
15,59,Will there be a federal charge filed against H...,will-there-be-a-federal-charge-filed-against-h...,US-current-affairs,2021-01-02T00:00:00Z,True,127476.154269,0.13149,"[""Yes"", ""No""]","[""0.0000002365760136311761420505896616707271"",...","[""13335616915502503908960482263427811070742976...",1333561691550250390896048226342781107074297618...
25,73,Will Donald Trump tweet announcing that he won...,will-donald-trump-tweet-announcing-that-he-won...,US-current-affairs,2020-11-05T00:00:00Z,True,127490.669491,3.295904,"[""Yes"", ""No""]","[""0.000001969126198486787442291877571524744"", ...","[""76182894856278632248939743050168442512633640...",7618289485627863224893974305016844251263364038...
27,75,Will the Ethereum 2.0 Genesis Event happen suc...,will-the-ethereum-20-genesis-event-happen-succ...,Crypto,2020-12-02T00:00:00Z,True,560270.423771,7.877976,"[""Yes"", ""No""]","[""0.9999991353509498666949062749530927"", ""0.00...","[""77627371401939105002385145056688905915571707...",7762737140193910500238514505668890591557170756...
29,77,Will Donald Trump formally concede the 2020 US...,will-donald-trump-formally-concede-the-2020-us...,US-current-affairs,2020-12-01T00:00:00Z,True,454342.990794,8688.076983,"[""Yes"", ""No""]","[""0.0000001590260745451327528785858607902578"",...","[""73163434197768416862075961184775012109464929...",7316343419776841686207596118477501210946492901...

Error for market 57: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=72218237979282777228049705424647682506448885729323094146056564018197398411018&fidelity=60
Error for market 59: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=1333561691550250390896048226342781107074297618285636393912534214135261982511&fidelity=60
Error for market 73: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=76182894856278632248939743050168442512633640389366255006450765930375044831481&fidelity=60
Error for market 75: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=77627371401939105002385145056688905915571707561396568073129144307944860669891&fidelity=60
Error for market 77: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=73163434197768416862075961184775012109464929015046649243834802132939776088568&fidelity=60
Error for market 87: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=7053350362338797277059166571288981948633575220839560632680187681584985045991&fidelity=60
Error for market 93: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=103418234926404024254858900863964281148590595298761113398435707275424060969494&fidelity=60
Error for market 1547: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=17850044851962347407075814589470280915206053818103595049300006021975237878634&fidelity=60
Error for market 13107: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=99447534956100618771876621778187442361055577351273860449814110734531753618312&fidelity=60
Error for market 34767: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=28919385929787831268910305769384819948982388203029298953403465551433615887391&fidelity=60
Error for market 35976: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=77158330250107127675074472535188248686309208295961442556266976755540808288146&fidelity=60
Error for market 40935: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=84105611680314297714312260106896378298243391309074334051570350511074615222778&fidelity=60
Error for market 42404: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=31496297711698493115657333639482583539189940690686854540546380825436255224517&fidelity=60
Error for market 215374: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=63623112617987706092276437115686984074032937973524508344873171357881304667333&fidelity=60
Error for market 239068: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=32296784534394932073862641920252276801381957812546091300533545502734649106089&fidelity=60
Error for market 239610: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=100291802474730057475490777026251147682730150896618859147456775856893519899911&fidelity=60
Error for market 239633: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=22920959462505296723291744979046931169757477227555505092006894503752659317234&fidelity=60
Error for market 239697: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=67480517040838128440925401508350079605522109453228556029915430151389055011364&fidelity=60
Error for market 239704: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=5042348561442365256884173711308438611710312882119878755276247184159786868366&fidelity=60
Error for market 239718: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=11919731357543471153973528651390398382912217846480656264970561830245421583765&fidelity=60
Error for market 240402: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=84046872862749438624466600704306190530247610595273848407029940872631982239323&fidelity=60
Error for market 240403: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=99000230530043308781322744153678478648282932611617063886016301848408621752647&fidelity=60
Error for market 240404: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=85093263336068945374274305170577286537967054417323850278413530511591707776238&fidelity=60
Error for market 240405: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=102089521439271930876130098876044645633039477265757329168388432902916067891382&fidelity=60
Error for market 240406: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=105364609353069125375900099192339277274211197283165943329365459545754786602548&fidelity=60
Error for market 240414: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=78826525983137135246023790612617841585029982024056021707853741103555989827223&fidelity=60
Error for market 240415: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=87925989301015700280151831708802135172173242232797156711742424006459808658066&fidelity=60
Error for market 240478: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=100803970877834506569481145482551974520295351174992382171748363810331746325773&fidelity=60
Error for market 240482: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=21757727066346337512552238381770937760836675076259879875996049259540172106446&fidelity=60
Error for market 240483: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=36024018246020870676711573799846137912111028175741687373133315054106662609464&fidelity=60
Error for market 240484: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=79789875865533098622594847444931974503133814618603323639559313905745585412154&fidelity=60
Error for market 240487: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=99203320429297314699847067475223127443982913509286214636321970294104102505714&fidelity=60
Error for market 240495: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=68579739046850079671322691260901483527445617855682647784935481824301132890083&fidelity=60
Error for market 241116: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=57957163456448497933195555273715386755706951841598217443217308595776240782800&fidelity=60
Error for market 241119: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=18015442242106699460988390678173091156901493557481620044108530187281980061715&fidelity=60
Error for market 241953: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=6543871533532352235236898438585712523307990606059826181959281340239059246670&fidelity=60
Error for market 241980: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=21684495601381510329456450367912002651654686423980996224939366074924182896671&fidelity=60
Error for market 242079: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=90460556716006578276523571432479651131057338393385059348922640227459447029301&fidelity=60
Error for market 242085: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=99086239833079230804472379174766489320717252111961344571267138631331697127180&fidelity=60
Error for market 242086: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=101281086836928007556506250772587361148714668745548113196832489884057578630555&fidelity=60
Error for market 243101: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=102818743276494865877486351201541971423562289017642366047426567962032397828824&fidelity=60
Error for market 243195: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=65066347942861019963792086655206889533357737082734237870635602945896552331006&fidelity=60
Error for market 243250: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=92553070790497228892830442191325476224909927216934769303892774455031083159837&fidelity=60
Error for market 243312: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=48815413813541497364593304760518528773312979083989998659474344768976426519909&fidelity=60
Error for market 244807: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=12673275279350988976147022598980244137080159194950778325405104752378335992865&fidelity=60
Error for market 244808: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=98461592100276802656789785968504315760993613174018395307672809091739853431487&fidelity=60
Error for market 244918: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=17827318201074563387243450632629515726872244084991087439662230606694237452512&fidelity=60
Error for market 244942: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=45730054428005976364975481724853807136124198875508884658556258379658298669864&fidelity=60
Error for market 244960: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=57023648072007881533393003885278936122559340099286946195530098695463389922101&fidelity=60
Error for market 245280: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=25077521531641035886372565258349324557040587289231658099405261563690833415418&fidelity=60
Error for market 247434: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=76367271781617033542927057695631978764351498023458536612709252154369750217256&fidelity=60
Error for market 247437: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=10566526361337376009364702835578373646175992308164718345205860798656933109756&fidelity=60
Error for market 247440: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=69787794768366566882373455309706803811852165095539211931717362287021606471397&fidelity=60
Error for market 247448: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=62397677238715027405777939172956295913750177286479108415965948731192974666539&fidelity=60
Error for market 247455: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=3433446866059963757018830696937990389313638072177197747252961344890456523237&fidelity=60
Error for market 247549: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=90337715997626782264226886014893426443281017771813248340481828414257469744897&fidelity=60
Error for market 247550: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=110036673581901599214577574676303926393692285250157208916601081826608528564748&fidelity=60
Error for market 247551: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=12403478247306315040934384999035245254338721210633883724503522818381041094168&fidelity=60
Error for market 247552: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=44213643874935061256701701903733337763109269385575973854740102558112146869598&fidelity=60
Error for market 247564: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=64214112073929340974953229924513987237847019268158332652439637902788061837869&fidelity=60
Error for market 247565: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=77306573616845012770968144916896437251906237104592651399485939679888024793899&fidelity=60
Error for market 247577: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=28553679695593944716606660612973877082041481769627243072880491798008242838668&fidelity=60
Error for market 247578: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=17777648839992328211140543130965244199737920122205268872074993234924078072888&fidelity=60
Error for market 247645: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=52357757586408239672771507103007307286968144849542537990977300582448710153535&fidelity=60
Error for market 247647: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=72853782435723873749167915531592849191702079994671129367133491818883112776559&fidelity=60
Error for market 247648: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=42019063569113286078763940929796417580993011141215698312434233973284318337901&fidelity=60
Error for market 247649: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=36880579054533753997837260590127282346036943780656019715258943037902747140198&fidelity=60
Error for market 247740: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=98009083076009368811845676256024778024467620705216749543393804974564002747882&fidelity=60
Error for market 247744: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=41295124019425234424661605480976632001490915863675815926574923943077854692092&fidelity=60
Error for market 247748: 400 Client Error: Bad Request for url: https://clob.polymarket.com/prices-history?market=62864600705713235636450713608136607154216823441735305392230741838178132008115&fidelity=60
Price history rows: 0

Empty DataFrame
Columns: []
Index: []